[#15] Feat: 홈 페이지의 채널 메뉴 UI 구현
prgrms-fe-devcourse/FEDC5_DevNamu_eunsu pull request #18
Opened 2023-12-29 13:21 UTC by Kim-Jaemin420

## 📝작업 내용
tailwind를 사용하여 홈 페이지의 채널 메뉴 UI를 구현했습니다.
`shadcn`을 사용해보았으나, 원하는 UI 디자인을 지원해주지 않아 직접 구현하게 되었습니다.
우선, figma의 디자인과 유사하게 구현하였고 추후 디자인 논의가 이루어지면 수정하도록 하겠습니다.

### 스크린샷
<img width="1063" alt="스크린샷 2023-12-29 오후 10 16 04" src="https://github.com/prgrms-fe-devcourse/FEDC5_DevNamu_eunsu/assets/61978339/385a0c96-d014-4860-b6cc-41fea8d506d9">

## 💬리뷰 요구사항
1. 현재 `pages` 디렉토리 내의 페이지들은 `Page` 접미사 없이 생성되어 있습니다.
> ex) `pages/Home`, `pages/MyNotifications` 등등

그런데, 내부의 index 파일에서는 컴포넌트가 `Page` 접미사와 함께 정의되어 있습니다.
> ex) const HomePage = () => {};

이 부분은 하나로 통일하여 디렉토리 명과 export 하는 컴포넌트 이름을 동일하게 맞출 필요가 있을 것 같습니다. 이 부분에 대해 의견 주시면 그에 맞게 수정하도록 하겠습니다.

2. 공통되는 스타일을 함수를 사용하여 분리했습니다. `tailwind` 사용이 익숙지 않아, 적절한 방법을 사용한 것인지 확인해주시고 리뷰해주시면 감사하겠습니다 : )

close #15

2023-12-29 20:09 UTC, seongbin9786 requested changes

2023-12-29 20:09 UTC, seongbin9786 commented on src/components/Home/ChannelMenu.tsx
> +            무능 게시판
p1) 사이드바 리뷰에서 말씀 드렸는데요, 하드 코딩은 지양 부탁드립니다 :)

동시에 코드 중복입니다.

2023-12-29 20:09 UTC, seongbin9786 commented on src/pages/Home/index.tsx
> +export default Home;
p2) 파일명과 컴포넌트 이름을 일치시켜야 하는 이유가 없어 보입니다.
- Page postfix가 없으면 import할 때 구분하기 어렵습니다.
- 파일명은 디렉토리 폴더에 위치되므로 이름 상의 정보 중복을 제거합니다.

2023-12-29 20:09 UTC, seongbin9786 commented on src/components/Home/ChannelMenu.tsx
> +const ChannelMenu = () => {
p3) 이름이 추상적이어서 코드를 보기 전까지 역할이 명확하지 않네요
- `Menu`는 Dropdown, Tab, GlobalNav, Popper, Sidebar 등 어디든 들어갈 수 있는 이름입니다.
- e.g. `ChannelSwitchTab`, `ChannelNavigationTab`

2023-12-30 03:48 UTC, Kim-Jaemin420 commented on src/components/Home/ChannelMenu.tsx
> +            무능 게시판
저는 개인적으로 중복이 들어가더라도 컴포넌트 내부에서 관리되는 것이 좀 더 가독성이 좋다고 생각해서요. 분리했을때 오히려 가독성이 떨어진다는 생각이 들어서, 분리할 필요가 있나 하는 생각이 드네요.

2023-12-30 03:50 UTC, Kim-Jaemin420 commented on src/App.tsx
> +          <Route path="channel/*" element={<HomePage />} />
이 부분은 아래처럼 수정을 했습니다. 탭을 눌렀을때 url이 `/channels/채널명` 으로 들어가는게 더 자연스러울 것 같아서요.
```js
<Route path="channels/*" element={<HomePage />} />
```

2023-12-30 03:51 UTC, Kim-Jaemin420 commented on src/components/Home/ChannelMenu.tsx
> +const ChannelMenu = () => {
이 부분은 동의합니다. `ChannelNavigationMenu`로 수정하겠습니다.

2023-12-30 03:53 UTC, Kim-Jaemin420 commented on src/pages/Home/index.tsx
> +export default Home;
어차피 `Pages`는 라우터 부분에서만 import 되어서 구분이 어려울 일이 있나 하는 생각이 들긴 하네요. 다른 분들도 비슷한 의견이라면 일치시키지 않겠습니다.

2023-12-30 04:53 UTC, seongbin9786 approved these changes

2024-01-01 01:47 UTC, jae-hun-e reviewed
LGTM👍
리뷰 한 번 확인해주시면 approval하겠습니다!

2024-01-01 01:47 UTC, jae-hun-e commented on src/App.tsx
> +          <Route path="channel/*" element={<HomePage />} />
재민님 -> ChannelNavigationMenu안에 path도 channels 변경되야 할 것 같습니다! 
성빈님 -> 제가 잘 이해한건지 모르겠는데 home내에서 라우팅 한 다는게 channels/compliment, channels/cheering, channels/incompetent 로 라우팅 되도록 할 수 없는지 여쭤본거 맞나요??

2024-01-01 01:47 UTC, jae-hun-e commented on src/components/Home/ChannelNavigationMenu.tsx
> +const getNavLinkClass = (isActive: boolean) =>
함수로 분리하신것이 가독성 좋아지고 잘 하신것 같습니다!!👍👍

다만 이런식으로 백틱을 이용하면 길어지게 되었을 때 가독성이 안좋아지고 앞에 적은 string값과 겹치는 속성인 경우 무시되는 경우가 있습니다. 

가독성과 안정성을 위해서 utils의 cn을 이용하여

```javascript
const getNavLinkClass = (isActive: boolean) =>
  {cn(`text-gray-600 rounded-t-md hover:bg-gray-100 hover:text-gray-800 text-center text-lg font-medium px-4 py-3 border border-b-0`, isActive ? "bg-gray-100" :"")};
```
이렇게 변경하는게 좀 더 좋을 것 같습니다!

2024-01-01 02:38 UTC, Kim-Jaemin420 commented on src/components/Home/ChannelNavigationMenu.tsx
> +const getNavLinkClass = (isActive: boolean) =>
오 그렇군요! 알려주셔서 감사합니다~~굳굳

2024-01-01 02:48 UTC, jae-hun-e approved these changes

2024-01-01 02:48 UTC, jae-hun-e commented on src/components/Home/ChannelNavigationMenu.tsx
> +};
빠른 수정 감사합니다ㅎㅎ👍👍

2024-01-01 02:52 UTC, merged